apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: learning-platform
data:
  MONGODB_URI: "mongodb://mongodb-service:27017"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  N8N_HOST: "n8n-service"
  REDIS_HOST: "redis-service"