apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: learning-platform
type: Opaque
data:
  # Générer avec: echo -n "votre_password" | base64
  POSTGRES_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=
  JWT_SECRET:andrvdXNlcl9zZWNyZXRfa2V5
  MONGODB_USER: bW9uZ29kYl91c2Vy
  MONGODB_PASSWORD: bW9uZ29kYl9wYXNzd29yZA==